CREATE TABLE cne.cnes (
	id serial4 NOT NULL,
	cne_id int4 NOT NULL,
	community_id int4 NOT NULL,
	nome varchar NULL,
	logo_arquivo int4 NULL,
	tipologia int2 NULL,
	managers_it jsonb NULL,
	data_criacao text NULL,
	data_inst text NULL,
	cnpj text NULL,
	estrategia_desc text NULL,
	estrategia_data text NULL,
	outcomes_it jsonb NULL,
	"createdAt" timestamp NULL,
	"updatedAt" timestamp NULL,
	"deletedAt" timestamp NULL,
	versao varchar(10) DEFAULT 'draft'::character varying NOT NULL,
	atuacao_aplica bool NULL,
	atuacao_naplica_just text NULL,
	intitutions_it jsonb NULL,
	estrategia_arquivo int4 NULL,
	CONSTRAINT cnes_pk PRIMARY KEY (id)
);